### PR TITLE
SOC-5620 Comment on an activity doesn't work in mobile application

### PR DESCRIPTION
**Pull request by trongtt**

### CODE REVIEW

**Comment by trongtt** [comment]
@wkhessairi Could you double check ? It is still working for me.

**Comment by thomasdelhomenie** [comment]
Just did a test, it is working as expected for me too (in browser and mobile app). When I click on the activity, I switch to the activity detail.

**Comment by wkhessairi** [comment]
@trongtt @thomasdelhomenie Yes you are right, we are well redirected to the single activity view. But we have another minor issue:

**Steps to reproduce in mobile view:**
- post some activities in the timeline
- click on an activity => the activity is displayed alone + comment input : OK
- click on cancel => comment input disappears + scroll to top : OK
- scroll down the activity => the scroll always returns back to top : NOK

=> I think the scroll is looping for all activities, we should restrict scrolling top only for the current activity.

**Comment by wkhessairi** [comment]
Another issue, in desktop view (not mobile):
- click on the comment button => comment input is displayed : OK
- click again on the same button => nothing happens : NOK
The expected result is that the comment input is closed.

**Comment by trongtt** [comment]
@wkhessairi yes, I realized the two minor issues you mentioned as following:
1/ [Mobile] We can not make scrolling well after cancel the comment form.

I will try to make a fix for first problem (1).

2/ [Desktop] Second click on comment icon doesn't close the comment form.

I did this behavior change intentionally because it makes more sense for me actually. Instead I propose to show the Cancel button in the comment form, to make it consistently both in Mobile and Desktop mode.
WDYT ? @wkhessairi  @thomasdelhomenie

**Comment by wkhessairi** [comment]
For "2/" point, I also would prefer a cancel button like on mobile view. Imagine that an activity have too many comments, and user wants to cancel its comment input, he has to scroll too much to top in order to reach the comment button to close the input.
But this is not what the spec says :( @thomasdelhomenie WDYT ?

**Comment by thomasdelhomenie** [comment]
It is a functional change, so we need @hghorbel opinion on this. But I kind of remember we already had this conversation with Hamadi and we decided to not add a Cancel button in comments. @hghorbel WDYT ?

**Comment by hghorbel** [comment]
Yes, It helps when we have too much comments to get rapidly the top comment, on the other hand, the decision was to conserve the Cancel button **Only** for mobile.

**Comment by trongtt** [comment]
@hghorbel I'm not sure to get your answer actually.

So what should we do now to close the comment form in Desktop mode ?
- Currently it requires second click on comment icon to close the form.
- Proposal: Consistently show the Cancel button to close the form.

**Comment by hghorbel** [comment]
@trongtt we keep it as currently it requires second click on comment icon to close the form.

**Comment by wkhessairi** [comment]
OK for me

**Comment by thomasdelhomenie** [comment]
Looks good, except that the mentioning does not work for me on my Android mobile (in the eXo app and in a browser).

**Comment by thomasdelhomenie** [comment]
The issue with mentioning is related to the keyboard and the landscape mode. When the keyboard is displayed, the height becomes smaller than the width, so the mentioning component thinks (yes a component can think !) it is in landscape mode. And in landscape mode we disable the mentioning. When I hide the keyboard, I can see the suggestion list again.
We will open a dedicated issue for that since it is not directly related to the current issue.

**Pull request merged**
