### PR TITLE
SOC-6019 delete translation on label of hidden button

### PR DESCRIPTION
**Pull request by boubaker**
Delete useless translation of the label of a hidden button. This button is used in JS file and that is used to send event using another displayed button.  See it here:

https://github.com/exodev/social/blob/develop/webapp/resources/src/main/webapp/javascript/eXo/social/webui/UIBannerUploader.js#L33

### CODE REVIEW

**Comment by trongtt** [comment]
I don't get what makes you think this is useless instead of a missing translation issue ? The label is not displayed on UI ?

**Comment by boubaker** [comment]
> If so, shouldn't we remove it completely ?

Can't do, it's ued here:

https://github.com/exodev/social/blob/develop/webapp/resources/src/main/webapp/javascript/eXo/social/webui/UIBannerUploader.js#L33

**Comment by thomasdelhomenie** [comment]
ok, so please update the commit message and the PR description to make it clear that the label is not used but that we can't remove it since it is still used under the hood.

**Comment by boubaker** [comment]
> ok, so please update the commit message and the PR description to make it clear that the label is not used but that we can't remove it since it is still used under the hood.

done

**Pull request merged**
