### PR TITLE
PLF-6849 : Deadlock found when trying to get lock

### PR DESCRIPTION
**Pull request by aboughzela**
No need to start transaction for read opertion

### CODE REVIEW

**Comment by thomasdelhomenie** [comment]
Do you know the root cause of the deadlock ?
Hibernate requires any operation which runs against the database to be done inside a transaction, so in any case there must be a transaction, even for read operations. So even if we remove these annotations, the queries will be done inside a transaction if a transaction has been started by a calling method, or it will probably fails if no transaction has been started (unless the auto-commit mode is enabled).

**Comment by aboughzela** [comment]
If you don't declare transaction  explicitly, then each statement will have to be executed in a separate transaction (autocommit mode). This may even lead to opening and closing one connection per statement.

Declaring a service as @Transactional will give you one connection for the whole transaction duration, and all statements will use that single isolation connection. This is way better than not using explicit transactions in the first place.

JPA doesn't enforce transactions on read operations. 
In Spring @Transactional allows you to mark read-only transactions, which has a great performance benefit. 
We need to improve our transnational API to allow use  read-only  (JCR use read-only connection for read operation : setReadOnly(true) will be called on the JDBC Connection) 
see https://javasight.wordpress.com/2009/02/22/transaction-optimization-for-read-only-transaction-spring-readonly-attribute/
WDYT ?

**Comment by thomasdelhomenie** [comment]
> If you don't declare transaction explicitly, then each statement will have to be executed in a separate transaction (autocommit mode). This may even lead to opening and closing one connection per statement.

Yes, agreed, that the point of my previous comment.

> Declaring a service as @ExoTransactional will give you one connection for the whole transaction duration, and all statements will use that single isolation connection. This is way better than not using explicit transactions in the first place.

Agreed of course.

> JPA doesn't enforce transactions on read operations.
In Spring @Transactional allows you to mark read-only transactions, which has a great performance benefit.
We need to improve our transnational API to allow use read-only (JCR use read-only connection for read operation : setReadOnly(true) will be called on the JDBC Connection)
see https://javasight.wordpress.com/2009/02/22/transaction-optimization-for-read-only-transaction-spring-readonly-attribute/

Definitely. I would be a nice perf improvement.

That being said, do we know the exact root cause of the current issue ?

**Comment by boubaker** [comment]
The "autocommit" mode is not recommended:
https://docs.jboss.org/hibernate/orm/4.2/manual/en-US/html/ch03.html
The usage of readonly mode on java.sql.Conection could be a good alternative in fact.

**Pull request closed without merging**
