### PR TITLE
SOC-5815 Fix recent users activities title

### PR DESCRIPTION
**Pull request by boubaker**
When a user adds any activity, the recent activities stream displays only "Contact information has been updated" message. This is due to a modification made in UIRecentActivity.gtmpl by SOC-4920 that will display this message for any type of activity independently from real activity title and body.
The fix consists of reverting the changes made and fix the original problem by allowing the translation of "Contact information has been updated" activity types.

### CODE REVIEW

**Comment by boubaker** [comment]
ok, the profile updates is made multi valued

**Comment by thomasdelhomenie** [comment]
It is better now, the updates are multi-valued but I have a weird behavior:
* I update my contact information -> "Contact information has been updated" activity is displayed in Recent Activities, OK
* I post an activity "Hello" in my activity stream -> new activity is added in my recent activities, OK
* I update the "About me" section in my profile, I have the following Recent Activities : 
1. an activity with
"About me" has been updated. 
Contact information has been updated
2. then the activity "Hello"

whereas IMO I should have:
1. an activity with
"About me" has been updated. 
2. then the activity "Hello"
3. 1 activity with
Contact information has been updated

WDYT ?

**Comment by thomasdelhomenie** [comment]
You mean it was the same behavior in previous versions ?

**Comment by boubaker** [comment]
> You mean it was the same behavior in previous versions ?

Yes. It's the same activity with comments added into it, for all profile updates.

**Comment by thomasdelhomenie** [comment]
ok

**Pull request merged**
